services:
  redis:
    image: redis:7
    container_name: lpr_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - lpr_redis_data:/data

  minio:
    image: minio/minio:latest
    container_name: lpr_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - lpr_minio_data:/data

volumes:
  lpr_postgres_data:
  lpr_minio_data:
  lpr_redis_data:
